require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe YoutubeVideosController do

  # This should return the minimal set of attributes required to create a valid
  # YoutubeVideo. As you add validations to YoutubeVideo, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "youtube_id" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # YoutubeVideosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all youtube_videos as @youtube_videos" do
      youtube_video = YoutubeVideo.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:youtube_videos)).to eq([youtube_video])
    end
  end

  describe "GET show" do
    it "assigns the requested youtube_video as @youtube_video" do
      youtube_video = YoutubeVideo.create! valid_attributes
      get :show, {:id => youtube_video.to_param}, valid_session
      expect(assigns(:youtube_video)).to eq(youtube_video)
    end
  end

  describe "GET new" do
    it "assigns a new youtube_video as @youtube_video" do
      get :new, {}, valid_session
      expect(assigns(:youtube_video)).to be_a_new(YoutubeVideo)
    end
  end

  describe "GET edit" do
    it "assigns the requested youtube_video as @youtube_video" do
      youtube_video = YoutubeVideo.create! valid_attributes
      get :edit, {:id => youtube_video.to_param}, valid_session
      expect(assigns(:youtube_video)).to eq(youtube_video)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new YoutubeVideo" do
        expect {
          post :create, {:youtube_video => valid_attributes}, valid_session
        }.to change(YoutubeVideo, :count).by(1)
      end

      it "assigns a newly created youtube_video as @youtube_video" do
        post :create, {:youtube_video => valid_attributes}, valid_session
        expect(assigns(:youtube_video)).to be_a(YoutubeVideo)
        expect(assigns(:youtube_video)).to be_persisted
      end

      it "redirects to the created youtube_video" do
        post :create, {:youtube_video => valid_attributes}, valid_session
        expect(response).to redirect_to(YoutubeVideo.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved youtube_video as @youtube_video" do
        # Trigger the behavior that occurs when invalid params are submitted
        YoutubeVideo.any_instance.stub(:save).and_return(false)
        post :create, {:youtube_video => { "youtube_id" => "invalid value" }}, valid_session
        expect(assigns(:youtube_video)).to be_a_new(YoutubeVideo)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        YoutubeVideo.any_instance.stub(:save).and_return(false)
        post :create, {:youtube_video => { "youtube_id" => "invalid value" }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested youtube_video" do
        youtube_video = YoutubeVideo.create! valid_attributes
        # Assuming there are no other youtube_videos in the database, this
        # specifies that the YoutubeVideo created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(YoutubeVideo).to receive(:update).with({ "youtube_id" => "MyString" })
        put :update, {:id => youtube_video.to_param, :youtube_video => { "youtube_id" => "MyString" }}, valid_session
      end

      it "assigns the requested youtube_video as @youtube_video" do
        youtube_video = YoutubeVideo.create! valid_attributes
        put :update, {:id => youtube_video.to_param, :youtube_video => valid_attributes}, valid_session
        expect(assigns(:youtube_video)).to eq(youtube_video)
      end

      it "redirects to the youtube_video" do
        youtube_video = YoutubeVideo.create! valid_attributes
        put :update, {:id => youtube_video.to_param, :youtube_video => valid_attributes}, valid_session
        expect(response).to redirect_to(youtube_video)
      end
    end

    describe "with invalid params" do
      it "assigns the youtube_video as @youtube_video" do
        youtube_video = YoutubeVideo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        YoutubeVideo.any_instance.stub(:save).and_return(false)
        put :update, {:id => youtube_video.to_param, :youtube_video => { "youtube_id" => "invalid value" }}, valid_session
        expect(assigns(:youtube_video)).to eq(youtube_video)
      end

      it "re-renders the 'edit' template" do
        youtube_video = YoutubeVideo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        YoutubeVideo.any_instance.stub(:save).and_return(false)
        put :update, {:id => youtube_video.to_param, :youtube_video => { "youtube_id" => "invalid value" }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested youtube_video" do
      youtube_video = YoutubeVideo.create! valid_attributes
      expect {
        delete :destroy, {:id => youtube_video.to_param}, valid_session
      }.to change(YoutubeVideo, :count).by(-1)
    end

    it "redirects to the youtube_videos list" do
      youtube_video = YoutubeVideo.create! valid_attributes
      delete :destroy, {:id => youtube_video.to_param}, valid_session
      expect(response).to redirect_to(youtube_videos_url)
    end
  end

end
